### ISSUE TITLE
Update terraform

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf-infrastructure#108]
Update s3 buckets
<img width="886" alt="Screenshot 2022-06-14 at 08 17 50" src="https://user-images.githubusercontent.com/34686298/173517108-08ee8edb-c235-4751-aae9-0c002ba5f7ad.png">

More details to come

**Comment by BreakingPitt** [comment]
@peterdudfield Maybe you can take a look at IAC sec tools like tf-sec by aquasecurity or checkov , to improve the security over the aws resources created with Terraform
