### ISSUE TITLE
Run data tailor satellite once a day

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf-infrastructure#143]
## Detailed Description
Run the data tailor service once a day using a new scheduled task

## Context
https://github.com/openclimatefix/Satip/pull/138#pullrequestreview-1197355996 - new option to only run data tailor clean up

## Possible Implementation
New task in 
https://github.com/openclimatefix/nowcasting_infrastructure/blob/main/terraform/modules/services/sat/schedule.tf

**Comment by jacobbieker** [comment]
Maybe every 12 hours? Just to make sure it stays a clean workspace?

**Comment by peterdudfield** [comment]
sounds good, 6 and 6?

**Comment by jacobbieker** [comment]
Yeah, sounds good!

**Comment by jacobbieker** [comment]
Possibly we should also only run satellite every 10-15min? Its still taking like 20min because of the data tailor. Not sure if there is a way to change that from the Satip app when RSS is not available or not

**Comment by peterdudfield** [comment]
Lets close this for now?
