### ISSUE TITLE
Check lat lons not rounded

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf-infrastructure#167]
The current lat longs in the new PV database are rounded to 2 decimal place.

In the nowcasting database some are not. These should be updated in the new database

we can also check by using the sheffield solar api - https://github.com/openclimatefix/PVConsumer/blob/main/pvconsumer/solar_sheffield_passiv.py#L43

- secrets are [here](https://eu-west-1.console.aws.amazon.com/secretsmanager/secret?name=development%2Fconsumer%2Fsolar_sheffield&region=eu-west-1)

**Comment by peterdudfield** [comment]
We should bare in mind we should not publicily give out the lat lons, as they are private information. Rounded to 2 decimal places will help that. In the public release of data we rounded to 4 decimal places

**Comment by devsjc** [comment]
Just to confirm Peter - do you want anything that's 4dp in nowcasting db rounding down to 2dp, or anything that's 2dp in pvsite db rounding up to 4dp?

**Comment by peterdudfield** [comment]
we want to make sure the lat lons are not being rounded in our db, so check they are all 2dp

**Comment by devsjc** [comment]
Feels like the two halves of your sentence contradict each other there - surely putting them all to 2dp *is* rounding them, if they are sometimes 4dp?

>  check they are all 2dp

I can put a condition on the column to make it so.

**Comment by peterdudfield** [comment]
Sorry i said that wrong, check that they are all 4 dp

**Comment by devsjc** [comment]
Here's the results of the check:

| Table                                    | Rounding                        |
|----------------------------|------------------------|
|`pvsiteproduction.sites` | 2 d.p. |
| `pvproduction.pv_system` | 2 or 4 d.p. |

So to clarify, is the task now to update those values in `pvsiteproduction.sites` with the non rounded versions from the sheffield solar API? This thread has confused me!

**Comment by peterdudfield** [comment]
Yea sorry, I might have confused myself here. 

I now think 2.d.p is fine. So perhaps we dont need to do anything here
