### ISSUE TITLE
Should we make ML bucket public 

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf-infrastructure#177]
## Detailed Description
Should we make ML S3 bucket public  (read only). This is basically the same as putting it on hugging face, although harder to find. This will help with CI, as we dont need to pass AWS credentials into CI. 

This would be for the `nowcasting-national-forecaster-models-development` bucket

Opinions @devsjc @jacobbieker

**Comment by jacobbieker** [comment]
Why not just put the models on Huggingface? Or if it's data, could also put most of it on there

**Comment by peterdudfield** [comment]
> Why not just put the models on Huggingface? Or if it's data, could also put most of it on there

Yea we could also do that

**Comment by jacobbieker** [comment]
I think since the rest of our models are there and to keep them as easy for others to use, I'd really prefer that

**Comment by peterdudfield** [comment]
Ill close this, as we are moving most models to HF when public
