### ISSUE TITLE
Add pv site database clean up

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf-infrastructure#205]
## Detailed Description
Add a new service that runs a database clean up

## Context
The pvsite database gets pretty big, so we only want to keep the most recent data in there.
Later ee will save data in S3, to make sure we have full history

## Possible Implementation
- simple to other services that run on `Faragate` as a cron job
- Docker: https://hub.docker.com/r/openclimatefix/pvsite_database_cleanup/tags
- Run once a day at midnight
- Env vars are: `DB_URL`
- Entry point is already defined in docker file

**Comment by simlmx** [comment]
Keep an eye out for the command that is run:
https://github.com/openclimatefix/pv-site-production/blob/main/infrastructure/Dockerfile.database-cleanup#L21

I'm not 100% sure that the date inline command will work as expected.

Also it's set to 3 days, we could decide to keep more or less.

**Comment by peterdudfield** [comment]
this now works on dev
