### ISSUE TITLE
change metrix to run at midnight

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf-infrastructure#212]
## Detailed Description
Currently metrics run at 13.00 every day, but wna this to run out midnight. 

## Context
- dont want an update of these values, as the `adjuster` uses this

## Possible Implementation
- change this code - https://github.com/openclimatefix/ocf-infrastructure/blob/main/terraform/modules/services/metrics/schedule.tf#L7

**Comment by devsjc** [comment]
Prod updated with #236
