### ISSUE TITLE
Need to request the "updated" (day-behind) PV_Live later in the day

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/ocf-infrastructure#219]
## Describe the bug

Since the start of 2023's British Summer Time (2023-03-26), the OCF production database (in rows where `regime='day-behind'`) contains the "wrong" values. Specifically, the DB (where `regime='day-behind'`) contains values which are not the same as values pulled today directly from PV_Live for that same period.

Instead, since 2023-03-26, the OCF DB contains almost identical values for `regime='day-behind'` and `regime='in-day'` for PV_Live.

I think the problem is fairly simple: I think that, since the 2023 transition to BST, our code runs too early in the day. Our code tries to fetch the "updated" PV_Live _before_ the updated PV_Live is ready from Sheffield. So our code _thinks_ it's getting the "updated" estimates from PV_Live. But it's _actually_ just getting (almost) a duplicate of the "in-day" PV_Live!

I'll provide a bunch of analysis of the data further down this bug report. But before I get there, I should mention some implications of this bug:

## Implications of mistakenly getting "in-day" PV_Live when we _think_ we're getting "updated" PV_Live:

I think this bug could (at least partially) explain why we sometimes get surprised by the size of our forecast errors in production! 

Our models are trained to predict "updated" PV_Live (as they should be!). But, the production DB contains PV_Live data labelled as "updated" PV_Live data, but which is _actually_ "in-day" PV_Live! And "intraday" PV_Live _often_ underestimates national PV by ~1 GW (at the peak for the day)!  So, when we compute our performance metrics in production, we're comparing our forecasts against the wrong version of PV_Live! So our forecasts look like they're > 1 GW wrong, when actually our forecasts might be doing a great job of predicting the _updated_ PV_Live, but the problem is that we're (unfairly) comparing our predictions to "intraday" PV_Live!

And this bug might help explain why "the adjuster" doesn't seem to help in an R&D testing environment, but does help in production. In production, maybe "the adjuster" is currently making our forecasts what it (falsely) believes is the 'truth', so maybe - since the start of BST - the adjuster is making our predictions more like intra-day PV_Live (which is bad, because intra-day PV_Live isn't very accurate!)

## Data analysis

Sol kindly pulled the entire OCF DB table into a CSV for me yesterday.

And, for comparison, I re-downloaded PV_Live data directly from the PV_Live API this morning.

Below is a _good_ period of data (7 days in August 2022), when the system was behaving itself. This is what the data _should_ look like :). Note that the "Updated national (from OCF DB)" (orange line) and the "Updated national (from PV Live API)" (green line) are perfectly aligned (_so_ perfectly aligned that the only way to see the orange line under the green line is by the orange 'x' marker!)

![image](https://user-images.githubusercontent.com/460756/235217705-9f09c0fd-b6aa-4034-bdb4-9500cea9a01f.png)

Below is a _bad_ period of data (7 days in April 2023). Note that the "Updated national (from OCF DB)" no longer aligns with the "updated" PV_Live I downloaded today fresh from the PV_Live API:

![image](https://user-images.githubusercontent.com/460756/235218864-2c956d20-29fb-477d-b0f9-6120defe7dd5.png)

Below is a zoom into one of the "bad" days above. I honestly have no idea why the "Updated national (from OCF DB)" is different from _both_ other lines. Maybe Sheffield Solar gradually update their estimate, so we're seeing a partially updated estimate?!

![image](https://user-images.githubusercontent.com/460756/235220359-4559f7fa-cab4-4206-896b-f26238b3560f.png)

Below is an analysis of the entire timeseries in the OCF DB. This plot shows the maximum absolute error per day of the "updated" estimate in the OCF DB, compared with the data I downloaded from the PV_Live API today. Several things to note from this plot:

1. The error was high for the first couple of months of the service, when the service grabbed the updated PV_Live at 10:45am UTC.
2. Then the errors (almost) completely go away after [git commit c4ee7cc](https://github.com/openclimatefix/ocf-infrastructure/commit/c4ee7cc36d068a01d23294d02466ddec74f7f912) on 2022-08-03 which pushed the update time to 11:30am UTC.
3. Things work well for (most of) the remainder of winter.
4. Things start to get a bit worse after the end of BST on 2022-10-30.
5. Things get a lot worse after the start of BST on 2023-03-26.

![image](https://user-images.githubusercontent.com/460756/235220828-f65785fb-953d-48ce-a103-18c794a31a73.png)

Finally, here are the absolute errors for comparisons of the other two pairs of datasets. Perhaps the main thing to note here is the bottom subplot, which shows that the difference between updated PV_Live and actual PV_Live is often ~1 GW, and can be > 1.6 GW.

![image](https://user-images.githubusercontent.com/460756/235221891-c72ec5f3-4daf-4bb1-a1c1-2f6bd847da71.png)

## Related

* I asked the good folks at Sheffield Solar when we should be pulling the "updated" PV_Live: https://github.com/SheffieldSolar/PV_Live-API/issues/20
* [Here's the line of our code](https://github.com/openclimatefix/ocf-infrastructure/blob/main/terraform/modules/services/gsp/schedule.tf#L37) which defines when we access the "updated" PV_Live.
* The code used to create these plots is [here](https://github.com/openclimatefix/analysis_of_pv_live/blob/main/notebooks/plot_error_between_intraday_PV_Live_and_updated_PV_Live.ipynb).

**Comment by peterdudfield** [comment]
Thanks Jack for all this work. 

See this [code](https://github.com/openclimatefix/ocf-infrastructure/blob/main/terraform/modules/services/gsp/schedule.tf#L69) for when the national GSP data is pulled. There is a split between the National and GSP, as they are run at different times by Solar Sheffield. 

You can also notice this [code](https://github.com/openclimatefix/GSPConsumer/blob/main/gspconsumer/app.py#L93) we only runs code when the BST hour is correct. This is define [here](https://github.com/openclimatefix/ocf-infrastructure/blob/main/terraform/modules/services/gsp/ecs.tf#L124) so only runs if between 10-11 UK time. This is confirmed in cloudwatch [here](https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logsV2:log-groups/log-group/$252Faws$252Fecs$252Fconsumer$252Fgsp$252F/log-events/streaming$252Fnational-day-after$252F0ac52d0f20184a9c818d08358306e5f4) and [here](https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logsV2:log-groups/log-group/$252Faws$252Fecs$252Fconsumer$252Fgsp$252F/log-events/streaming$252Fnational-day-after$252F11cd907d2a744582b74f81a56aba5566). So National PVlive values are being pulled at 10.45 UK time. 

My understanding was that PVlive National was ran at 10.30, so 10.45 should be fine. I agree there is definately a problem, and caused by the clock change

**Comment by peterdudfield** [comment]
One quick solution is we just pull the National data every 5 mins from PVlive for one day, and just see when it changes. This could be done manually one day

**Comment by JackKelly** [comment]
> One quick solution is we just pull the National data every 5 mins from PVlive for one day, and just see when it changes. This could be done manually one day

That's a great idea! I'll do that (locally on my PC) ASAP (probably tomorrow).

**Comment by JackKelly** [comment]
[Here's my very simple script](https://github.com/openclimatefix/analysis_of_pv_live/blob/main/scripts/poll_PV_Live_API.py) for downloading data from PV_Live every 15 minutes and saving locally.

**Comment by JackKelly** [comment]
[Here's a detailed analysis](https://github.com/SheffieldSolar/PV_Live-API/issues/22#issuecomment-1535144787) of the data I've been downloading from PV_Live every 15 mins.

**Comment by JackKelly** [comment]
> Idea is to change it to 10.45 UTC

After discussion with Peter in Slack, and after Jack's analysis of the downloaded PV_Live data, we've decided to download the "updated PV_Live national" at 11:00 UTC. This is also when [the new PV_Live README](https://github.com/SheffieldSolar/PV_Live-API#notes-on-pv_live-gb-national-update-cycle) suggests we downloaded the updated estimate.

**Comment by peterdudfield** [comment]
this on dev, now, so at 11 UTC we will be able to see the difference, at least for yestrday

**Comment by peterdudfield** [comment]
Yea this worked, and def different was 700 MW instead of 200MW. Ill deploy this on production

**Comment by JackKelly** [comment]
Sounds good!

Will this confuse "the adjuster" (for the next few days, while the OCF DB updates itself? Maybe it'll be fine...)

**Comment by peterdudfield** [comment]
It won't confuse the adjuster, but it will take 7 days for the results to fully improve. 
To speed this up, we could update the `gsp_yields` values in the database for the last seven days. 
Probably not a bad thing to do anyway, have a script that can over write then `gsp_yield` values

**Comment by JackKelly** [comment]
> we could update the gsp_yields values in the database for the last seven days

SGTM!

**Comment by peterdudfield** [comment]
This is now down, and we see differences and its BST right now
