### ISSUE TITLE
Research and Implement Basic Security Measures

### ISSUE THREAD

**Issue by flowirtz** [openclimatefix/ocf-infrastructure#22]
Could include:

- AWS Config
- AWS Security Hub
- moving all security rules to a `nowcasting-security` workspace in TF
- ...?

**Comment by flowirtz** [comment]
https://github.com/bridgecrewio/checkov

Could also look into Sentinel policies, but that seems a bit hardcore for now, maybe

**Comment by peterdudfield** [comment]
We went with Auth0, closing this for now
