### ISSUE TITLE
Update database once Consumer is done

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf-infrastructure#299]
## Detailed Description
How to update the `input_data_last_updated` once a consumer has run.

## Context
- this table stores the most recent time the nwp, pv, sat, gsp, e.t.c has run
- currently most consumer update the `input_data_last_updated`. see [here](https://github.com/openclimatefix/PVConsumer/blob/main/pvconsumer/app.py#L122)
- new NWP Consumer doesnt do this

## Possible Implementation
- add into new nwp consumer
- add into `dag` to get it to do this, would need to give it DB_URL access

**Comment by peterdudfield** [comment]
yea, I'll try and write something and see how neat it looks in the dag

**Comment by devsjc** [comment]
Seems like less code duplication and seperation that way as well - one reuseable task vs several individual implementations in seperate microservices.

**Comment by peterdudfield** [comment]
Ill close this for now, as we do update this through the API now
