### ISSUE TITLE
merge UK 2 platforms

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf-infrastructure#302]
## Detailed Description
We currently have two platforms for the UK
- national and GSP 
- site
Should we merge these two in the infrastructure code?

## Context
- good to keep things clean
- both projects have some overlapping components like NWP Consumer
- new India project soon. 
- The airflow system could also come together?
- we might not want to do this if NG-ESO or other client want to deploy National/GSP themselves

## Possible Implementation
- just merge the development.tf files and production.tf for both projects. 
- might be able to use resources rather than loading them in

**Comment by peterdudfield** [comment]
@devsjc what do you think to this?

**Comment by devsjc** [comment]
Yes, I think this is a good idea.

**Comment by peterdudfield** [comment]
Do you think we need to save any data from the database? Perhaps we can download a backup before we move it over, and then we can always reload data if we need to

**Comment by devsjc** [comment]
Always worth it, yeah.

**Comment by peterdudfield** [comment]
Have moved airlfow platform into uk-nowcasting

**Comment by devsjc** [comment]
^ On development, at least

**Comment by devsjc** [comment]
- [x] Deleted all leftover resources managed by pvsite-development workspace. Workspace can now be deleted.
- [x] Deleted no longer used buckets and secrets in development

**Comment by devsjc** [comment]
PVSite workspaces deleted with https://github.com/openclimatefix/ocf-infrastructure/pull/348
