### ISSUE TITLE
Add readme to uk-nowcasting 

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf-infrastructure#349]
## Detailed Description
Would be good to add a read me to the development and production

## Context
- good to have good docs

## Possible Implementation
- say what it is, what componnents are in it
- add a diagram of both things, for example - 
- perhaps we update one from here - https://docs.google.com/presentation/d/1LHZZ7AjfJFGmi3GYiVufI7BGETllI5ug3LO7tvaccdQ/edit#slide=id.g1502fe07f55_0_0
- or create a new one

**Comment by devsjc** [comment]
https://github.com/openclimatefix/ocf-infrastructure/pull/354

**Comment by peterdudfield** [comment]
Ill close this for now, as there is faiurly good readme in there now
