### ISSUE TITLE
Seperate Sentry DSN for API

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf-infrastructure#371]
## Detailed Description
Add two different sentry dsn, one for each api

## Context
- sentry projects show erros, but need different dsn
- currerntly all going to nowcasting_api sentry project

## Possible Implementation
- add new terraform var
- ask @braddf for new sentry dsn for sites api

**Comment by devsjc** [comment]
Recieved new DSN from @braddf. See https://github.com/openclimatefix/ocf-infrastructure/pull/372

**Comment by devsjc** [comment]
Applied in TFCloud: https://app.terraform.io/app/openclimatefix/workspaces/nowcasting_infrastructure_production-eu-west-1/runs/run-1r2GAgGSJtFtWWHv
