### ISSUE TITLE
Upgrade to python 3.12

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf-infrastructure#373]
## Detailed Description
Would be good to upgrade to pyhton 3.11, to keep up wiht the latest. We could even go python 3.12?

## Context
- good to keep up to date

## Possible Implementation
- Upgrade docker file
- Check that CI works
- This could be done in lots of repos like 

| Repo                                                                                           | Python version | Image version | dev | pro
| ------------------------------------------------------------ | --------------- | -------------- | --- | --- |
| https://github.com/openclimatefix/nwp-consumer                  | 3.12 | | 
| https://github.com/openclimatefix/Satip                                  | 3.11 |2.11.17 | yes
| https://github.com/openclimatefix/PVConsumer   					 |3.11 |1.0.1 | yes 
| https://github.com/openclimatefix/GSPConsumer                   | 3.12 | 1.1.13 | yes
| https://github.com/openclimatefix/pv-site-api                         | 3.11| 1.0.16|  yes
| https://github.com/openclimatefix/uk-pv-national-gsp-api     | 3.11                |1.5.35 | yes |
| https://github.com/openclimatefix/pv-site-production            | | 
| https://github.com/openclimatefix/uk-pv-national-xg             | 3.11|  1.0.25 | yes | yes
| https://github.com/openclimatefix/uk-pv-forecast-blend        | 3.12 | 0.0.22 | yes
| https://github.com/openclimatefix/pvnet_app                          | | 
| https://github.com/openclimatefix/uk-analysis-dashboard     | 3.12 | a5026bb | yes
| .github| 3.12|
| pvsite-datamodel | 3.11 | 1.0.4
| dagster-dags                                                                             | | | |

**Comment by peterdudfield** [comment]
I've reoppened this, as we might want to upgrade other repos too

**Comment by peterdudfield** [comment]
Thanks @jacobbieker and @dev for jumping on on this

**Comment by peterdudfield** [comment]
Looks like there is an speed up on national-forecast. @devsjc any chance you could upgrade this on production?

**Comment by devsjc** [comment]
Sure thing - deployed with [run-2Sm138iE1oDjTbd9](https://app.terraform.io/app/openclimatefix/workspaces/nowcasting_infrastructure_production-eu-west-1/runs/run-2Sm138iE1oDjTbd9)

**Comment by peterdudfield** [comment]
Ill close this for the moment, and we can reopen when we need to
