### ISSUE TITLE
Update site forecast to get full 36 hours NWP

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf-infrastructure#426]
## Detailed Description
Make sure its getting the full NWPs, not just 8 hours

## Context
Making worst forecasts

**Comment by zakwatts** [comment]
![image](https://github.com/openclimatefix/ocf-infrastructure/assets/47150349/941a0117-d9e6-4ccc-a700-3d1768d32fd3)

**Comment by zakwatts** [comment]
![image](https://github.com/openclimatefix/ocf-infrastructure/assets/47150349/a91ee219-51e4-4bcb-ae34-9c4b76d2fe74)

**Comment by zakwatts** [comment]
<img width="825" alt="Screenshot 2024-02-08 at 16 42 07" src="https://github.com/openclimatefix/ocf-infrastructure/assets/47150349/461fceb0-274e-47ce-8f1f-0dbd0685f4d7">

**Comment by zakwatts** [comment]
Appears a large change in the forecast over a day (around 30%)

**Comment by zakwatts** [comment]
see: 
![image](https://github.com/openclimatefix/ocf-infrastructure/assets/47150349/6af4845d-7e70-42a3-8d23-caee2f9b1cc5)
vs
![image](https://github.com/openclimatefix/ocf-infrastructure/assets/47150349/edb28f19-6f5b-4821-96e9-862ebe820e9b)

**Comment by zakwatts** [comment]
same site but peak on 7th Feb goes from 0.13 to 0.21
