### ISSUE TITLE
Change `api`, `api_sites`, `internal_ui` to use `eb_app`

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf-infrastructure#444]
## Detailed Description
Change `api`, `api_sites`, `internal_ui` to use `eb_app`.  

## Context
- good to reduce code

## Possible Implementation
- in nowcasting/development, use eb_app not all the other ones,
- delete old applications

**Comment by devsjc** [comment]
Very happy to see us move towards standardised module usage! Great stuff @peterdudfield, just what I was hoping for when making the eb_app module, but haven't had the time to get round to doing yet :)
