### ISSUE TITLE
Remove pnvet1 from inf readme.md

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf-infrastructure#466]
Remove Pvnet1 from readme in nowcasting/development and nowcasting/production

**Comment by roshnaeem** [comment]
Hello @peterdudfield, can I take this one?

**Comment by peterdudfield** [comment]
Of course

**Comment by roshnaeem** [comment]
Hello @peterdudfield, this issue is already addressed by 2 PRs #473 and #472. I think we can close this issue.
