### ISSUE TITLE
create a india usergroup

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf-infrastructure#488]
Create a usergroup that has full access to the following services in `ap-south-1`:
- ECS
- S3
- Secrets manager
- Cloudwatch
- Elastic beanstalk
- RDS
- EC2

The name could be {region}-developer

It would be great to create this as a general terraform component, then we can import this into the different regions

We can then manually add users to this group

**Comment by aryanbhosale** [comment]
> Create a usergroup that has full access to the following services in `ap-south-1`:
> 
> * ECS
> * S3
> * Secrets manager
> * Cloudwatch
> * Elastic beanstalk
> * RDS
> * EC2
> 
> The name could be {region}-developer
> 
> It would be great to create this as a general terraform component, then we can import this into the different regions
> 
> We can then manually add users to this group

should I create a new file in ```ocf-infrastructure/tree/main/terraform/india/development``` with the general code?

**Comment by peterdudfield** [comment]
I'd probably create a seperate module in [here](https://github.com/openclimatefix/ocf-infrastructure/tree/main/terraform/modules)  called user_groups. And then it can be used in india/development

**Comment by aryanbhosale** [comment]
under user_groups, do I have to make just one main.tf for ap-south-1?
and in india/development, will it be used in main.tf or anywhere else also?

**Comment by peterdudfield** [comment]
yea, I would just have a main, and it takes in a region. How you done much terraform before?

**Comment by aryanbhosale** [comment]
> yea, I would just have a main, and it takes in a region. How you done much terraform before?

I haven't done Terra form at all before, the dashboard issue was my first one.
Ill try to make the main.tf file

**Comment by aryanbhosale** [comment]
does 2012-10-17 version work for this? or are we using newer versions?

**Comment by peterdudfield** [comment]
we are on terraform `1.7`

**Comment by aryanbhosale** [comment]
> we are on terraform `1.7`

Okay thank you

**Comment by aryanbhosale** [comment]
I've raised a PR, could you please review it #496

**Comment by aryanbhosale** [comment]
> I've raised a PR, could you please review it #496 

Should I add steps on how to use it for adding other regions ?
