### ISSUE TITLE
Add region to dags

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf-infrastructure#522]
Add region at the start of dag name
This should be `uk` or `india`

For example in line26 https://github.com/openclimatefix/ocf-infrastructure/blob/main/terraform/modules/services/airflow/dags/india/forecast-site-dag.py

adn similar in these folders
- https://github.com/openclimatefix/ocf-infrastructure/tree/main/terraform/modules/services/airflow/dags/india
- https://github.com/openclimatefix/ocf-infrastructure/tree/main/terraform/modules/services/airflow/dags/uk

This will help make it really clear if there is an error, where it is from

**Comment by peterdudfield** [comment]
It turn out we need to add them to the `task_id`, in order for the slack messages to show what did error

**Comment by aryanbhosale** [comment]
> It turn out we need to add them to the `task_id`, in order for the slack messages to show what did error

#526 fixes this, could you please review it, ive also noticed that the ocf_infractructure repo uses datetime.utcnow() which is deprecated, should i open a new issue to replace it with more timezone aware functions?

**Comment by peterdudfield** [comment]
yea, repalce `datetime.utcnow() would be great`, do you mind opening an issue or PR for this?

**Comment by aryanbhosale** [comment]
> yea, replacing `datetime.utcnow() would be great`, do you mind opening an issue or PR for this?

Ill open an issue and work on it

**Comment by aryanbhosale** [comment]
> THanks, I just tried to deploy the latest changes
> 
> I saw that `task_definition` also changed. This should be changed back. Its actually linked to the AWS task deifnition name. Ive reverted the changes on `main`, but if you fancied doing those changes again, but only on `task_id`, that would be great. If not, im happy to do it

Oh my bad, ill make the changes

**Comment by aryanbhosale** [comment]
> THanks, I just tried to deploy the latest changes
> 
> I saw that `task_definition` also changed. This should be changed back. Its actually linked to the AWS task deifnition name. Ive reverted the changes on `main`, but if you fancied doing those changes again, but only on `task_id`, that would be great. If not, im happy to do it

Ive corrected it in #527 , sorry for the unnecessary task definition change

**Comment by aryanbhosale** [comment]
> yea, replacing `datetime.utcnow() would be great`, do you mind opening an issue or PR for this?

ive opened a PR #528 , will work on it
