### ISSUE TITLE
Deprecation of datetime.utcnow()

### ISSUE THREAD

**Issue by aryanbhosale** [openclimatefix/ocf-infrastructure#528]
## Describe the bug

ocf-infrastructure is currently using the deprecated '''datetime.utcnow()''' from the ```datetime``` python library. It would be good to use a timezone-aware function that'll work for ```python3.11^``` and won't change the current functionality

## Possible implementation

One possible modification would be `datetime.now(tz=timezone.utc)` where timezone is imported from datetime

**Comment by peterdudfield** [comment]
> Hi @peterdudfield , why does it show that a terraform test failed? any idea? is it my code or something else? ![image](https://private-user-images.githubusercontent.com/36108149/325957111-80f9b1b8-0f53-4dcf-b812-fc63e3425a89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzE2MTIsIm5iZiI6MTcxNDEzMTMxMiwicGF0aCI6Ii8zNjEwODE0OS8zMjU5NTcxMTEtODBmOWIxYjgtMGY1My00ZGNmLWI4MTItZmM2M2UzNDI1YTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDExMzUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NmFhMWU5Y2MxZTA2ODIyYmI4MzlhYWFlMzAzYzcwZjA2ZGMyNTQxZDJlMGY2YWQwMWZhOTZlZDQ1ZmM0M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VsTf15wsYTpIxuh1kcbP6gkrXN5VBCOMaLlPQwbdR40)

No dont worry about that, that'll be something else. I imagine it got cancelled manually

**Comment by aryanbhosale** [comment]
> > Hi @peterdudfield , why does it show that a terraform test failed? any idea? is it my code or something else? ![image](https://private-user-images.githubusercontent.com/36108149/325957111-80f9b1b8-0f53-4dcf-b812-fc63e3425a89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzE2MTIsIm5iZiI6MTcxNDEzMTMxMiwicGF0aCI6Ii8zNjEwODE0OS8zMjU5NTcxMTEtODBmOWIxYjgtMGY1My00ZGNmLWI4MTItZmM2M2UzNDI1YTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDExMzUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NmFhMWU5Y2MxZTA2ODIyYmI4MzlhYWFlMzAzYzcwZjA2ZGMyNTQxZDJlMGY2YWQwMWZhOTZlZDQ1ZmM0M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VsTf15wsYTpIxuh1kcbP6gkrXN5VBCOMaLlPQwbdR40)
> 
> No dont worry about that, that'll be something else. I imagine it got cancelled manually

Oh okay, thank you

**Comment by aryanbhosale** [comment]
Hi @peterdudfield , #530 is the fix for this, could you please review this?
Thank you
