### ISSUE TITLE
Update to latest docker platform

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf-infrastructure#561]
## Detailed Description
It would be great to update the AWS elastic beanstalk application to use the latest docker platform

## Context
- this will update 2 Apis, airflow instance, and the internal dashboard
- good to use the most update data platform

## Possible Implementation
Code is here https://github.com/openclimatefix/ocf-infrastructure/blob/main/terraform/modules/services/eb_app/eb.tf#L33

**Comment by BreakingPitt** [comment]
@peterdudfield is this done?

**Comment by peterdudfield** [comment]
It looks like its on [3.8.3](https://github.com/openclimatefix/ocf-infrastructure/blob/main/terraform/modules/services/eb_app/eb.tf#L33), but i think there is now a later version
