### ISSUE TITLE
decrease National-xg model to run every 2 hours

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf-infrastructure#572]
We have now deployed a new model that predictions up to 36 hours ahead. 

We can now reduce the times that nationa-xg model runs to every 2 hours. Eventually we will turn this off.

The cron job [here](https://github.com/openclimatefix/ocf-infrastructure/blob/main/terraform/modules/services/airflow/dags/uk/forecast-national-dag.py#L29) needs updating

**Comment by peterdudfield** [comment]
@Sukh-P do you think this is sensible now we have pvnet day ahead running?

**Comment by Sukh-P** [comment]
Yeah this sounds sensible no we have the PVNet day ahead model deployed
