### ISSUE TITLE
run new metrics for adjuster at night time

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf-infrastructure#672]
Currerntly we calculate new adjuster values int he middle of the day. 
This happens after we have got the updated PVlive values.

However this can cause a discontinuity in the forecast. The 12.00 foercast has different adjuster values than the 13.00 foercast, as an example. 
We could be run the metrics (to get the adjuster values) at 21.00 instead, and would cause less of a jump

**Comment by zakwatts** [comment]
The jumps between AM and PM make more sense now. 

Just having a quick look at Sheffield Solar PV estimate:
![Screenshot 2024-11-07 at 16 45 17](https://github.com/user-attachments/assets/baad29ce-b018-43d8-8791-e8c4b9e269fa)

The "Actual Outturn" appears to be released live. Perhaps theres information we could use during the day to have a more accurate adjustor. or even, could we not also pass this information as a lag feature to our models?

@peterdudfield If you know, are these Actual Outturn values that I can see in the screenshot different intraday vs say 24 hours into the future. I've checked the Actual outturn values for yesterday and they match our "PV_Live Updated values".

I'm going to attach some screenshots of the values to see if they change from today to tomorrow.
![Screenshot 2024-11-07 at 16 52 19](https://github.com/user-attachments/assets/7641ab84-87f2-44f4-bc60-d4278f72de97)

![Screenshot 2024-11-07 at 16 52 31](https://github.com/user-attachments/assets/76ade727-c2ca-46bc-84a6-74e154409103)

Would running at 21.00 mean that we might have less up to date information about the adjuster values? (even if this is the case... I think moving it to 21:00 to reduce the jumps sounds like a good idea.

**Comment by peterdudfield** [comment]
Yea, so running at 21.00 not 12.00 would mean, slightly less live information has been used. But it is the last 7 day average, so its ok. 

Ok, ill move it to 21.00
