### ISSUE TITLE
Make s3 eb bucket private

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf-infrastructure#79]
make elastic beanstalk bucket private

code is [here](https://github.com/openclimatefix/nowcasting_infrastructure/blob/main/terraform/modules/services/api/s3.tf#L3)

**Comment by peterdudfield** [comment]
Thanks @gmlyth for this work. 

I leave it open as [this eb s3](https://github.com/openclimatefix/nowcasting_infrastructure/blob/main/terraform/modules/services/data_visualization/s3.tf) folder also need to be made private

**Comment by gmlyth** [comment]
Sounds good! I'm just getting started with Terraform (more familiar with CloudFormation) so I'm going to do some more sandboxing and will take care of that if it's still open.

**Comment by peterdudfield** [comment]
Amazing thanks @gmlyth really appreciate you taking this on. Let me know if you need any terraform advice. Sounds like you are doing what I would do, which is diving in and trying it out
