### ISSUE TITLE
Data vis service - memoery

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf-infrastructure#96]
See the data vis service keeps crashing, could be due to memory
<img width="742" alt="Screenshot 2022-05-23 at 10 43 15" src="https://user-images.githubusercontent.com/34686298/169791967-bc2b7cb2-c696-40c9-82a6-e1d27c62b047.png">

**Comment by peterdudfield** [comment]
Yea, current solution is to rebuild the env,
<img width="679" alt="Screenshot 2022-05-23 at 13 49 24" src="https://user-images.githubusercontent.com/34686298/169822924-ba585c8a-1920-4ee2-bfaf-3992edd4f961.png">

**Comment by jacobbieker** [comment]
Ah okay, sounds good!
